name: RSS to Notion

on:
  schedule:
    # 每小时运行一次 (GitHub 免费版建议间隔不要低于 5-15 分钟)
    - cron: '0 * * * *'
  workflow_dispatch: # 允许手动点击运行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Script
        env:
          ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          RSS_INTERVAL_SECONDS: ${{ vars.RSS_INTERVAL_SECONDS || 3600 }}
          TIMEZONE_OFFSET: 0  # GitHub Action 使用 UTC 时间，不需要转换
        run: |
          python jiclaw.py "https://rss.etnews.com/06.xml" "https://idw-online.de/en/pressreleasesrss?langs=en_US&category_ids=15&category_ids=13&category_ids=4&category_ids=14&category_ids=1&category_ids=7&category_ids=12&category_ids=9&category_ids=3&category_ids=5&category_ids=8&category_ids=10&field_ids=302" "http://anysilicon.com/feed" "https://www.electronicdesign.com/__rss/website-scheduled-content.xml?input=%7b%22sectionAlias%22:%22home%22%7d" "https://entegrisinc.gcs-web.com/rss/news-releases.xml" "https://www.azonano.com/syndication.axd?news-cat=24" "https://semiwiki.com/feed/" "https://www.electronicsweekly.com/feed/" "https://feed.businesswire.com/rss/home/?rss=G1QFDERJXkJeEFpRXEMGSQ5SVFJdFUNdFkNaV1dDFUkQUhFUVl9dF0M=" "https://seekingalpha.com/listing/most-popular-articles.xml" "https://ir.appliedmaterials.com/rss/news-releases.xml" "https://www.tomshardware.com/feeds.xml" "https://thelec.net/rss/S1N3.xml" "https://www.trendforce.com/feed/Semiconductors.html" "https://www.trendforce.com/feed/LED.html" scraper:semi-insights scraper:icsmart scraper:aijiwei scraper:lam-research scraper:lumentum scraper:nvidia scraper:nvidia-dev scraper:intel scraper:coherent scraper:iccsz scraper:broadcom scraper:broadcom-blog
